BaseWars.LANG = {}

function BaseWars:AddLanguage(languageCode, languageName)
	local debugInfos = debug.getinfo(2)
	local d_source, d_line = debugInfos.short_src, debugInfos.currentline

	if not languageCode then
		ErrorNoHalt("Missing argument #1 for BaseWars:AddLanguage() » " .. d_source .. " @ line #" .. d_line .. "\n")

		return
	end

	if not languageName then
		ErrorNoHalt("Missing argument #2 for BaseWars:AddLanguage() » " .. d_source .. " @ line #" .. d_line .. "\n")

		return
	end

	languageCode = string.lower(languageCode)
	if BaseWars.LANG[languageCode] then
		ErrorNoHalt("Language \"" .. languageCode .. "\" already exists » " .. d_source .. " @ line #" .. d_line .. "\n")

		return
	end

	BaseWars.LANG[languageCode] = {
		languageName = languageName,
	}
end

function BaseWars:AddTranslation(key, languageCode, text)
	local debugInfos = debug.getinfo(2)
	local d_source, d_line = debugInfos.short_src, debugInfos.currentline

	if not key then
		ErrorNoHalt("Missing argument #1 for BaseWars:AddTranslation() » " .. d_source .. " @ line #" .. d_line .. "\n")

		return
	end

	if not languageCode then
		ErrorNoHalt("Missing argument #2 for BaseWars:AddTranslation() » " .. d_source .. " @ line #" .. d_line .. "\n")

		return
	end

	if not text then
		ErrorNoHalt("Missing argument #3 for BaseWars:AddTranslation() » " .. d_source .. " @ line #" .. d_line .. "\n")

		return
	end

	languageCode = string.lower(languageCode)
	if not BaseWars.LANG[languageCode] then
		ErrorNoHalt("Language \"" .. languageCode .. "\" does not exists, Use BaseWars:AddLanguage(\"" .. languageCode .. "\") before BaseWars:AddTranslation(\"" .. key .. "\", \"" .. languageCode .. "\", \"" .. text .. "\") » " .. d_source .. " @ line #" .. d_line .. "\n")

		return
	end

	if BaseWars.LANG[languageCode][key] then
		ErrorNoHalt("Translation key \"" .. key .. "\" already exists for language \"" .. languageCode .. "\", overiding with new value » " .. d_source .. " @ line #" .. d_line .. "\n")
	end

	BaseWars.LANG[languageCode][key] = text
end

function BaseWars:LanguageExists(languageCode)
	local debugInfos = debug.getinfo(2)
	local d_source, d_line = debugInfos.short_src, debugInfos.currentline

	if not languageCode then
		ErrorNoHalt("Missing argument #1 for BaseWars:LanguageExists() » " .. d_source .. " @ line #" .. d_line .. "\n")

		return
	end

	return BaseWars.LANG[languageCode] != nil
end

function BaseWars:GetLanguage(languageCode)
	if languageCode then
		return BaseWars.LANG[languageCode]
	end

	return BaseWars.LANG
end

BaseWars.LANG.Currency = "$"

BaseWars.LANG["fr"] = {
	languageName = "Français",
	selectPlayer = "Sélectionnez un joueur",
	error = "Erreur",
	close = "Fermer",
	notAllowed = "Vous n'avez pas la permission de faire cela",
	reloadThemes = "Vous avez rechargés vos thèmes.",
	choosePlayer = "Choisir joueur:",
	amount = "Montant",
	targetNotFound = "La cible n'a pas été trouvé",
	invalidArguments = "Argument invalide",
	invalidArgumentNumber = "Argument invalide, besoin d'un nombre",
	unlockalldoor = "Toutes les porte ont été déverrouillé.",
	yes = "Oui",
	no = "Non",
	none = "Aucune",
	search = "Recherche",
	add = "Ajouter",
	never = "Jamais",
	notYours = "Ce n'est pas à vous",
	all = "Tout",
	cancel = "Annuler",
	back = "Retour",
	now = "Maintenant",
	reset = "réinitialiser",
	favorites = "Favoris",

	-- Others
	levels_takeToLong = "Prévention crash, %s a pris beaucoup d'XP.",
	spawnmenu_reloaded = "Le spawnmenu à été rechargé",
	boughtCredits = "Vous avez reçu vos %s credits!",

	-- Calculator
	calculator_selectPrinter = "Sélectionnez une imprimante",
	calculator_priceToUpgrade = "Prix pour améliorer: %s",
	calculator_printerProduction = "Production: %s",
	calculator_calculate = "Calculer",
	calculator_printerUpgrades = "Amélioration d'imprimante",
	calculator_prestigeUpgrades = "Amélioration de prestige",

	-- Player Lookup (Admin menu)
	playerlookup_search = "Rechercher avec SteamID ou SteamID64",
	playerlookup_page = "Page %s/%s",
	playerlookup_prevPage = "Precedente Page",
	playerlookup_nextPage = "Prochaine Page",
	playerlookup_lastSeen = "Derniere session: %s",
	playerlookup_joined = "Première Connection: %s",
	playerlookup_playerNoData = "Ce joueur n'a aucune données",
	playerlookup_bounty = "Prime: %s (Stack » %s)",
	playerlookup_noProfileData = "No profile #%s",
	playerlookup_noProfileData = "Pas de profil #%s",
	playerlookup_kills = "Kills: %s",
	playerlookup_deaths = "Morts: %s",
	playerlookup_messageSent = "Messages sent: %s",
	playerlookup_playCount = "Play count: %s",
	playerlookup_moneyTaken = "Total money: %s",
	playerlookup_xpReceived = "Total XP: %s",
	playerlookup_messageSent = "Message envoyé: %s",
	playerlookup_playCount = "Nombre de session: %s",
	playerlookup_moneyTaken = "Argent total: %s",
	playerlookup_xpReceived = "XP total: %s",
	playerlookup_neverConnected = "This player has never logged in",

	-- Profile Selector
	profileSelector_profileNumber = "Profil #%s",
	profileSelector_money = "Argent:",
	profileSelector_level = "Niveau:",
	profileSelector_xp = "XP:",
	profileSelector_timePlayed = "Temps Joué:",
	profileSelector_prestige = "Prestige:",
	profileSelector_profileID = "ProfileID:",
	profileSelector_play = "Jouer",
	profileSelector_creatingProfile = "Création du profil...",
	profileSelector_wait = "Veuillez réessayer dans %s secondes",
	profileSelector_waitingForData = "En attente des données de vos profils",
	profileSelector_applyingProfile = "Veuillez patienter pendant que vos données soient appliquées",

	-- Context Menu
	contextmenu_game = "INTERACTIONS DU JEU",
	contextmenu_basewars = "INTERACTIONS DU BASEWARS",
	contextmenu_links = "LIENS IMPORTANTS",
	contextmenu_callAdmin = "Appeler un admin",
	contextmenu_clearDecals = "Clear Decals",
	contextmenu_stopSound = "Stopper Les Sons",
	contextmenu_adminMenu = "Menu Admin",
	contextmenu_cleanup = "Clean Up",
	contextmenu_respawn = "Vous Respawn",
	contextmenu_doClearDecals = "Cleared Decals",
	contextmenu_doStopSound = "Tout les sons on été stoppé",
	contextmenu_faction = "Factions",
	contextmenu_sellMenu = "Menu de Vente",
	contextmenu_rules = "Règles",
	contextmenu_prestige = "Prestige",
	contextmenu_warnings = "Warns",
	contextmenu_config = "Configuration",
	contextmenu_describeProblem = "Descrivez votre probleme en quelque mots",
	contextmenu_adminCalled = "Vous avez un appeler un admin pour «%s»",
	contextmenu_pendingTickets = "TICKETS EN ATTENTE",
	contextmenu_receivedTicket = "Vous avez reçu un ticket",
	contextmenu_alreadyClaimed = "Déjà Revendiqué",
	contextmenu_claim = "Revendiquer ticket",
	contextmenu_tp = "TP",
	contextmenu_goto = "GOTO",
	contextmenu_closeTicket = "Votre ticket à été fermé",
	contextmenu_playerLeft = "Le joueur à déconnecté",
	contextmenu_from = "De: %s",

	-- Admin Menu
	adminmenu_warnings = "Warnings",
	adminmenu_bans = "Bannissement",
	adminmenu_playerLookup  = "Joueurs",
	adminmenu_logs = "Logs",
	adminmenu_factionLeader = "Chef De Faction: %s",
	adminmenu_factionImmunity = "Immunitée De Faction: %s",
	adminmenu_factionMembers = "Membres De Faction:",
	adminmenu_disband = "Dissoudre",
	adminmenu_changeLeader = "Changer de chef",
	adminmenu_reset = "Réinitialiser",
	adminmenu_kick = "Expulser",
	adminmenu_noLongerLeader = "Vous n'êtes plus le chef de faction",
	adminmenu_doResetImmunity = "Vous avez réinitialisé l'immunitée de %s",
	adminmenu_doDisband = "Vous avez dissout la faction «%s»",
	adminmenu_changedLeader = "%s est maintenant le chef de \"%s\"",
	adminmenu_beenKicked = "Vous avez été expulsé de votre faction",
	adminmenu_kicked = "Vous avez expulser %s de la faction",
	adminmenu_immunityReset = "Votre immunitée à été réinitialisé",
	adminmenu_resetGlobalImmunity = "L'immunitée global à été réinitialisée par %s",
	adminmenu_globalImmunity = "Immunitée Globale: %s",

	-- Leaderboard
	leaderboard_title = {
		time_played = "Temps de jeu",
		money = "Les plus riches",
		prestige = "Plus haut prestige",
		level = "Plus haut niveau",
		kills = "Nombre de kills",
		deaths = "Nombre de morts",
		message_sent = "Message dans le chat",
		money_received = "Argent total",
		xp_received = "XP total",
		session_count = "Nombre de connections",
		kd = "Plus Haut KD"
	},

	-- Dashboard
	dashboard_bounties = "Primes",
	dashboard_staffOnline = "Staff En Ligne",
	dashboard_AllCommands = "Toutes Les Commandes",
	dashboard_copiedCommand = "Commande copiée",
	dashboard_commandExecuted = "Vous avez exécuté la commande «%s»",
	dashboard_noStaffOnline = "Aucun staff en ligne",
	dashboard_noBounties = "Aucune prime",

	-- Death Notices
	deathNotice_suicide = "%s s'est suicidé",
	deathNotice_noAttacker = "%s est mort à cause de %s",
	deathNotice_by = "%s à tué %s avec %s",
	deathNotice_fallDamage = "%s est mort de dégât de chute",

	-- SafeZone
	safeZone_spawnProp = "Vous ne pouvez pas faire spawn de prop en safe zone",
	safeZone_buy = "Vous ne pouvez pas acheter d'objet dans la safe zone.",
	safeZone_dropWeapon = "Vous ne pouvez pas drop d'arme dans la safe zone.",

	-- Blocked Zone
	blockedZone_cantGoThere = "Vous ne pouvez pas aller là.",

	-- Context Menu (C)
	contextmenu_disable = "Le context menu est désactivé pour le moment",

	-- Checkbox
	checkbox_on = "ON",
	checkbox_off = "OFF",

	-- Payday
	payday = "Jour de paye, vous recevez %s",
	paydayAFK = "Vous ne pouvez pas recevoir votre paye lorsque vous êtes AFK",

	-- HUD
	hud_level = "Niv: ",
	hud_spawnprotection = "Vous êtes invincible",
	hud_afkFor = "Vous êtes AFK depuis %s",
	hud_armed = "Armé",
	hud_unarmed = "Pas Armé",
	hud_youAreArmed = "Vous êtes armé",
	hud_youAreUnarmed = "Vous n'êtes pas armé",

	-- Bounty Command
	bounty_title = "Menu des primes",
	bounty_placeBounty = "Mettre une prime de %s sur la tête de %s",
	bounty_receivedBounty = "%s à reçu %s pour avoir tué %s qui avait une prime",
	bounty_placedOn = "%s a mis une prime de %s sur la tête de %s",

	-- Bank
	bank_upgrade = "Vous avez amélioré votre banque pour %s",
	bank_scan = "Scanner",
	bank_doscan = "Vous avez éffectué un scan, vous avez trouvé %s imprimantes",
	bank_waitscan = "Patienter pour le prochain scan (%ss)",
	bank_connectedMenu = "%s imprimantes connectées",
	bank_buyupgrade = "Vous avez acheté l'amélioration \"%s\" pour %s",
	bank_notYours = "Cette bank n'est pas le votre",
	bank_upgrades = {
		capacityName = "Capacité",
		capacityDesc = "Augmente la capacité de la banque.",
		healthName = "Vie",
		healthDesc = "Augmente la vie de la banque.",
	},

	-- Pay Command
	pay_title = "Menu Paye",
	pay_giveTo = "Donner %s à %s",
	pay_payedPlayer = "Vous avez donné %s à %s",
	pay_payedBy = "%s vous à donné %s",
	pay_noOneToPay = "Tu veux donner de l'argent à un fantome???",
	pay_cantPayBot = "Vous ne pouvez pas donner de l'argent a un bot",

	-- Sell Menu
	sellmenu_allEntities = "Toutes les entités",
	sellmenu_selectedEntities = "Entités selectionnées",
	sellmenu_sellallfor = "Vendre tout pour %s",
	sellmenu_sellselectedfor = "Vendre la sélection pour %s",
	sellmenu_sellDuringRaid = "Vous ne pouvez pas vendre pendant que vous êtes en raid",
	sellmenu_sell = "Vous avez vendu %s entités pour %s",
	sellmenu_sellTitle = "Vente",
	sellmenu_sellallText = "Vendre %s entitées pour %s",
	sellmenu_sellButton = "Vendre",

	-- BaseWars Menu (F3)
	bwm_dashboard = "Dashboard",
	bwm_leaderboard = "Leaderboard",
	bwm_faction = "Faction",
	bwm_raid = "Raid",
	bwm_sellmenu = "Vente",
	bwm_logs = "Logs",
	bwm_prestige = "Prestige",
	bwm_config = "Configuration",
	bwm_notificationsHistory = "Historique Notifs",

	-- Spawnpoint
	spawnpoint_nametitle = "Changer de nom",
	spawnpoint_name = "Nom (Entre 3 et 32 caractère)",
	spawnpoint_setname = "Mettre le nom «%s» à ce point d'apparition",
	spawnpoint_chose = "Choisissez votre spawn",
	spawnpoint_tooshort = "Le nom du point d'apparition est trop court",
	spawnpoint_toolong = "Le nom du point d'apparition est trop long",
	spawnpoint_howto = "Appuyer sur «%s» pour change le nom",
	spawnpoint_currentname = "Nom: %s",
	spawnpoint_notyours = "Ce point d'apparition n'est pas le votre",
	spawnpoint_choosebefore = "Choisissez un point d'apparition",
	spawnpoint_spawnatworld = "Réapparaitre au spawn du monde",

	-- Scoreboard
	scoreboard_goBack = "Retour",
	scoreboard_rank = "Grade: %s",
	scoreboard_faction = "Facton: %s",
	scoreboard_factionLeader = "Chef de Faction: %s",
	scoreboard_money = "Argent: %s",
	scoreboard_level = "Niveau: %s",
	scoreboard_prestige = "Prestige: %s",
	scoreboard_hp = "Vie: %s/%s",
	scoreboard_armor = "Armure: %s/%s",
	scoreboard_xp = "XP: %s/%s",
	scoreboard_kd = "K/D: %s/%s (%s)",
	scoreboard_ping = "Ping: %s",
	scoreboard_bounty = "Prime: %s",
	scoreboard_afk = "AFK: %s",
	scoreboard_god = "God: %s",
	scoreboard_cloak = "Cloak: %s",
	scoreboard_timeplay = "Temps Joué: %s",
	scoreboard_steamidCopied = "Vous avez copié le SteamID de %s",
	scoreboard_steamid64Copied = "Vous avez copié le SteamID64 de %s",
	scoreboard_nameCopied = "Vous avez copié le Nom de %s",
	scoreboard_steamid = "SteamID: %s",
	scoreboard_steamid64 = "SteamID64: %s",
	scoreboard = {
		name = "PSEUDO",
		level = "NIVEAU",
		prestige = "PRESTIGE",
		kills = "KILLS",
		deaths = "MORTS",
		ping = "PING",
	},

	-- Printer
	printer_takeMoney = "RETIRER L'ARGENT",
	printer_takeMoneyButton = "RETIRER %s",
	printer_superAdminBypass = "SuperAdmin Bypass",
	printer_notYours = "Cette imprimante n'est pas la votre.",
	printer_upgradeOnce = "AMÉLIORER 1 FOIS POUR %s",
	printer_upgradeMax = "AMÉLIORER %sx POUR %s",
	printer_maxupgrade = "Cette amélioration ne peut plus être acheté",
	printer_cantafford = "Vous n'avez pas assez pour vous permettre cela",
	printer_buyupgrade = "Vous avez acheté l'amélioration \"%s\" %s fois pour %s",
	printer_cantAffordUpgrade = "Vous n'avez pas assez d'argent pour acheter cette amélioration.",
	printer_VIPOnly = "VIP SEULEMENT",
	printer_upgrade = "Améliorer",
	printer_buypaper = "Acheter Papier",
	printer_buyPaperMenu = "ACHETER DU PAPIER",
	printer_buyPaperFor = "ACHETER %s PAPIER POUR %s",
	printer_full = "IMPRIMANTE PLEINE",
	printer_bank_full = "BANQUE PLEINE",
	printer_xp = "XP: %s",
	printer_paper = "Papier: %s/%s",
	printer_time = "Temps restant: %s",
	printer_noPrinterConnected = "Aucune imprimante connectée",
	printer_connectedToBank = "Connecté à une banque",
	printer_maxed = "MAX",
	printer_printOutOfPaper = "Imprimantes manque de papier",
	printer_quickUpgrade = "AMÉLIORATION RAPIDE",
	printer_quickUpgradeButton = "AMÉLIORER",
	printer_level = "NIVEAU",
	printer_price = "PRIX",
	printer_upgradeMenu = "AMÉLIORER",
	printer_tooExpensive = "TROP CHER",
	printer_upgrades = {
		intervalName = "Vitesse",
		intervalDesc = "Augmente la vitesse de l'imprimante. Reduit le temps d'impression de 0.05 seconde par amélioration.",
		amountName = "Quantité",
		amountDesc = "Augmente la quantité d'argent produit par l'imprimante.",
		capacityName = "Capacité",
		capacityDesc = "Augmente la capacité de l'imprimante.",
		paperCapacityName = "Capacité Papier",
		paperCapacityDesc = "Augmente la capacité de papier de l'imprimante.",
		autoPaperName = "Auto Papier",
		autoPaperDesc = "Rachète automatiquement du papier lorsque l'imprimante n'en a plus.",
	},

	-- Commands
	command_setMoney_set = "Vous avez mit l'argent de %s à %s",
	command_setMoney_setBy = "%s a mit votre argent à %s",
	command_addMoney_add = "Vous avez donné %s à %s",
	command_addMoney_addBy = "%s vous a donné %s",
	command_setPointshop_set = "Vous avez mit les pointshop de %s à %s",
	command_setPointshop_setBy = "%s a mit vos pointshop à %s",
	command_addPointshop_add = "Vous avez donné %s pointshop à %s",
	command_addPointshop_addBy = "%s vous a donné %s pointshop",
	command_setCredits_set = "Vous avez mit les credits de %s à %s",
	command_setCredits_setBy = "%s a mit vos credits à %s",
	command_addCredits_add = "Vous avez donné %s à %s credits",
	command_addCredits_addBy = "%s vous a donné %s credits",
	command_setPrestige_set = "Vous avez mit le prestige de %s à %s",
	command_setPrestige_setBy = "%s a mit vos prestige à %s",
	command_addPrestige_add = "Vous avez donné %s prestige à %s",
	command_addPrestige_addBy = "%s vous a donné %s prestige",
	command_setLevel_set = "Vous avez mis le niveau de %s à %s",
	command_setLevel_setBy = "%s a mit votre niveau à %s",
	command_addLevel_add = "Vous avez donné %s niveau à %s",
	command_addLevel_addBy = "%s vous a donné %s niveau",
	command_setXP_set = "Vous avez mis l'exp de %s à %s",
	command_setXP_setBy = "%s a mit votre exp à %s",
	command_addXP_add = "Vous avez donné %s exp à %s",
	command_addXP_addBy = "%s vous a donné %s exp",
	command_refund_refundPlayer = "Vous avez remboursé en totalité (%s)",
	command_refund_refundBy = "Vous avez été remboursé par %s",
	command_bot_spawn = "%s à fait apparaitre %s bots",
	command_bot_serverFull = "Serveur plein",
	command_bot_kick = "Vous avez kick tout les bots du server",
	command_dropWeapon_blackilst = "Cette arme est blacklist et ne peut donc pas être jetté au sol",
	command_respawn_respawn = "Vous avez faire réapparaître %s",
	command_respawn_respawnBy = "%s vous à fait réapparaître",
	command_reset_resetPlayer = "Vous avez réinitialiser les stats de %s",
	command_reset_resetBy = "Vos stats on été réinitialiser par %s",
	command_playerValue = "%s est valué à %s",
	command_raid_forceStopped = "Un raid à été arreté par %s (Admin)",
	command_raid_noRaid = "Il n'y a pas de raid en ce moment",
	command_god = "Godmode ON",
	command_ungod = "Godmode OFF",
	command_cloak = "Cloak ON",
	command_uncloak = "Cloak OFF",
	commands_deactivated = "Commande désactivé",
	commands_payTime = "Temps avant la prochaine paye: %s",
	command_clearNotifs = "Vous avez supprimé toutes vos notifications",
	commands_wrongPrefix = "Mauvais préfix, faites la commande «%s»",
	commands_commandDontExist = "La commande «%s» n'existe pas",
	commands_allDataDeleted = "Toutes vos données on été supprimé",
	commands_profileDataDeleted = "Tout vos profils on été supprimé",
	commands_deleteProfilesDataOf = "Vous avez supprimé tout les profils de %s",
	commands_deleteAllDataOf = "Vous avez supprimé toutes les données de %s",

	-- Raid
	raids_raidAlreadyGoingOn = "Un raid est déjà en cours",
	raids_globalImmunity = "Vous ne pouvez pas commencer un raid pendant l'immunité globale («%s»)",
	raids_raidYourself = "Vous ne pouvez pas vous raider vous-même...",
	raids_raidSoloWhileInFaction = "Vous ne pouvez pas raider une personne qui n'est pas dans une faction si vous en faites partie",
	raids_raidFactionWhileSolo = "Vous ne pouvez pas raider une personne qui est dans une faction si vous n'en faites pas partie",
	raids_raidFactionMate = "Vous ne pouvez pas raider une personne qui est dans votre faction",
	raids_yourLevelTooLow = "Votre niveau est trop bas («%s» niveaux manquants)",
	raids_opponentLevelTooLow = "Le niveau de votre adversaire est trop bas (%s niveaux manquants)",
	raids_factionImmunity = "La faction «%s» a encore son immunité (%s)",
	raids_playerImmunity = "Le joueur %s a encore son immunité (%s)",
	raids_raidStarted = "Un raid a commencé entre «%s» et «%s» initié par %s",
	raids_stopRaidWhenNoRaid = "Il n'y a pas de raid à arrêter",
	raids_stopRaidWhenNotInRaid = "Vous ne pouvez pas arrêter un raid si vous n'en faites pas partie",
	raids_stopRaidWhenNotAttacker = "Vous ne pouvez pas arrêter un raid si vous n'êtes pas l'attaquant",
	raids_stopRaidWhenNotLeader = "Vous ne pouvez pas arrêter un raid si vous n'êtes pas le chef",
	raids_raidStopped = "Le raid a été annulé par %s",
	raids_canceledByAdmin = "Le raid a été annulé par un administrateur",
	raids_finished = "Le raid est terminé",
	raids_cancelWhenPlayerDisconnect = "Le raid a été annulé parce que %s s'est déconnecté",
	raids_globalImmunity = "Immunité Globale: %s",
	raids_resetGlobalImmunity = "L'immunité globale a été réinitialisée",
	raids_yourImmunity = "Votre immunité a été réinitialisée",
	raids_youResetPlayerImmunity = "Vous avez réinitialisée l'immunité de %s",
	raids_playerImmunityAdmin = "%s immunity: %s",
	raids_cantShootPersonInRaid = "Vous ne pouvez pas tirer sur une personne qui est en raid",
	raids_destroyEntity = "Vous avez reçu %s pour avoir détruit «%s»",
	raids_buttons = {
		start = "Start a raid",
		stop = "Stop a raid"
	},

	-- Config
	config_number = "Nombre",
	config_vector_x = "X",
	config_vector_y = "Y",
	config_vector_z = "Z",
	config_string = "Texte",
	config_playerConfig = "Configuration Joueur",
	config_gamemodeConfig = "Configuration Gamemode",
	f3config = {
		showHUDName = "Afficher le HUD",
		showHUDDesc = "Afficher le HUD du gamemode",
		autoPrestigeName = "Auto Prestige",
		autoPrestigeDesc = "Automatiquement passer un prestige lorsque vous avez le niveau",
		autoSellOnLeaveName = "Vente Automatique",
		autoSellOnLeaveDesc = "Vendre automatiquement vos objets en quittent le jeu.",
		bluredBackgroundName = "Flou",
		bluredBackgroundDesc = "Le fond du menu F3/F4 est flouté.",
		damageOwnEntitiesName = "Endommager entitées",
		damageOwnEntitiesDesc = "Endommager vos propre entitées.",
		seeOtherPrinterName = "Voir les imprimantes",
		seeOtherPrinterDesc = "Voir l'interface des imprimantes des autres joueurs.",
		seeYourPrinterName = "Voir vos imprimantes",
		seeYourPrinterDesc = "Voir l'interface de vos imprimantes",
		languageName = "Langue",
		languageDesc = "Change la langue.",
		themeName = "Thème",
		themeDesc = "Change le theme.",
		showBuyPopupName = "Popup d'achat",
		showBuyPopupDesc = "Afficher un popup pour comfirmer un achat ou la raison de l'échec d'un achat dans le menu d'achat (%s).",
		closeOnBuyName = "Fermer après achat",
		closeOnBuyDesc = "Ferme le menu après un achat dans le menu d'achat (%s).",
		showAdvertsName = "Adverts",
		showAdvertsDesc = "Montrer les adverts dans le chat.",
		hideNonBuyableName = "Cacher les non achetable",
		hideNonBuyableDesc = "Cacher tous les items qui ne sont pas achetable dans le menu d'achat (%s).",
		hideEmptyCategoriesName = "Cacher les catégories",
		hideEmptyCategoriesDesc = "Cacher les catégories vides dans le menu d'achat (%s).",
		formatTimeDaysName = "Formatage du temps",
		formatTimeDaysDesc = "Formater le temps en jours [OFF: 65h 4m; ON: 2d 17h 4m]",
		factionHighlightName = "Surbrillance De Faction",
		factionHighlightDesc = "Mettre en surbrillance les membres de votre faction",
		showAllCommandsName = "Toutes les commandes",
		showAllCommandsDesc = "Afficher les commandes que vous n'avez pas accès dans le dashboard",
		F4TabName = "Onglet BaseWars Shop",
		F4TabDesc = "L'onglet sur lequel le shop va s'ouvrir",
	},

	-- BaseWars Shop (F4)
	bws_level = "Niveau: %s",
	bws_limit = "Limite: %s",
	bws_prestige = "Prestige: %s",
	bws_cantLevel = "Besoin du niveau %s",
	bws_cantMoney = "Besoin de %s",
	bws_cantPrestige = "Besoin du prestige %s",
	bws_cantVIP = "Besoin de %s",
	bws_cantRaid = "Raid seulement",
	bws_buyItem = "Vous avez acheté «%s» pour %s",
	bws_cantBuyBomb = "Vous pouvez seulement acheter des bombes durant un raid",
	bws_cantBuyDuringRaid = "Vous ne pouvez pas acheter cela pendant un raid",
	bws_printerCap = "Vous avez atteint votre limite de d'imprimante",
	bws_forWho = "Vous devez être %s pour acheter cet objet",
	bws_tooExpensive = "Vous ne pouvez pas vous permettre cela",
	bws_lowLevel = "Votre niveau est trop bas pour acheter cela",
	bws_reachLimit = "Vous avez atteint la limite de cette objet",
	bws_lowPrestige = "Vous n'êtes pas assez haut prestige pour cela",
	bws_copyBind = "Bind pour «%s» copié",
	bws_nothingToBuy = "Il n'y a rien que vous pouvez acheter.",
	bws_confirm = "Confirmer",
	bws_cancel = "Annuler",
	bws_understand = "Je comprend",
	bws_confirmPurchase = "Confirmation d'achat",
	bws_confirmError = "Erreur d'achat",
	bws_buyConfirm = "Acheter «%s» pour %s",
	bws_slowDown = "Trop vite! (%ss)",
	bws_addFavorite = "Vous avez ajouté «%s» dans vos favoris",
	bws_removeFavorite = "Vous avez retiré «%s» de vos favoris",
	bws_last = "Dernier Onglet",

	-- Faction
	faction_factionName = "Nom De Faction",
	faction_password = "Mot De Passe",
	faction_noFaction = "Sans Faction",
	faction_createFaction = "Créer Faction",
	faction_joinFaction = "Rejoindre Faction",
	faction_join = "Rejoindre",
	faction_quitFaction = "Quitter Faction",
	faction_quit = "Quitter",
	faction_changePassword = "Change Mot De Passe",
	faction_change = "Changer",
	faction_kickMember = "Expulser Un Membre",
	faction_kick = "Expulser",
	faction_promoteLeader = "Promouvoir Chef",
	faction_promote = "Promouvoir",
	faction_frendlyFire = "Tir allié",
	faction_createdFaction = "Vous avez crée votre faction «%s»",
	faction_alreadyInFaction = "Vous êtes déjâ dans un faction",
	faction_nameTaken = "La faction «%s» existe déjâ",
	faction_nameTooShort = "Nom de faction trop court",
	faction_dontExist = "La faction «%s» n'existe pas",
	faction_reachMemberLimit = "Cette faction contien le nombre maximum de membres (%s)",
	faction_wrongPassword = "Mauvais mot de passe",
	faction_playerJoinFaction = "Vous avez rejoin la faction «%s»",
	faction_playerJoinYourFaction = "%s a rejoin votre faction",
	faction_notInFaction = "Vous devez être dans un faction",
	faction_kickDisband = "Vous avez été Expulsé de votre faction car elle a été dissoute",
	faction_disband = "Vous avez quitter votre faction",
	faction_notLeader = "Vous n'êtes pas le chef de la faction",
	faction_passwordChanged = "Vous avez changé votre mot de passe de «%s» à «%s»",
	faction_cantDoToYourself = "Vous ne pouvez pas faire ca sur vous même",
	faction_differentFaction = "Vous n'êtes pas dans le même faction",
	faction_notMemberOfYourFaction = "%s ne fais pas parti de votre faction",
	faction_kickedPlayer = "Vous avez Expulsé %s de la faction",
	faction_kicked = "Vous avez été Expulsé de la faction",
	faction_promotedLeader = "Vous avez promu %s chef de la faction",
	faction_becameLeader = "Vous êtes devenu le chef de la faction",
	faction_leaderDisconnected = "Vous avez été Expulsé de votre faction car le chef a déconnecté",
	faction_passwordTooLong = "Mot de passe trop long",
	faction_nameTooLong = "Nom de faction trop long",
	faction_inRaid = "Vous ne pouvez pas faire cela pendant que vous êtes en raid",
	faction_changedFrendlyFire = "Tir allié: %s",
	faction_nameBlocked = "Vous ne pouvez pas créer de faction avec le nom «%s»",
	faction_cantJoinDuringRaid = "vous ne pouvez pas rejoindre un faction qui est dans un raid",
	faction_changedFrendlyFireAdmin = "Vous avez changé le tir allié de «%s» à: %s",

	-- Gamemode Config
	gamemodeConfig_updated = "La configuration du gamemode à été mis à jour.",
	gamemodeConfig_shortText = "Txt",
	gamemodeConfig_remove = "Retirer",
	gamemodeConfig_userGroup = "Grade",
	gamemodeConfig_weaponClass = "Classe d'arme",
	gamemodeConfig_entityClass = "Classe d'entitée",
	gamemodeConfig_tool = "Outil",
	gamemodeConfig_category = "Catégorie",
	gamemodeConfig_model = "Model",
	gamemodeConfig_steamID64 = "SteamID64",
	gamemodeConfig_saveConfig = "Sauvegarder",
	gamemodeConfig_resetConfig = "Réinitialiser",
	gamemodeConfig_PrinterPublicName = "Imprimante Public",
	gamemodeConfig_PrinterPublicDesc = "Quand désactivé seul le propriétaire d'une imprimante peut intéragir avec.",
	gamemodeConfig_PrinterPaperPriceName = "Prix Du Papier",
	gamemodeConfig_PrinterPaperPriceDesc = "Le prix d'un seul papier.",
	gamemodeConfig_SBoxWeapsName = "Armes Sandbox",
	gamemodeConfig_SBoxWeapsDesc = "Les joueurs apparaissent avec les armes de HL2.",
	gamemodeConfig_NotifyAllWhenConfigModifiedName = "Notifier Tout Le Monde",
	gamemodeConfig_NotifyAllWhenConfigModifiedDesc = "Notifier tout le monde quand un administrateur modifie la configuration du gamemode.",
	gamemodeConfig_BankRadiusName = "Distance De La Banque",
	gamemodeConfig_BankRadiusDesc = "La distance a la quel une banque peut détecter un imprimante, mettre à 0 pour une portée infinie.",
	gamemodeConfig_WalkSpeedName = "Vitesse De Marche",
	gamemodeConfig_WalkSpeedDesc = "La vitesse a laquel un jouer va quand il marche.",
	gamemodeConfig_RunSpeedName = "Vitesse De Course",
	gamemodeConfig_RunSpeedDesc = "La vitesse a laquel un joueur va quand il court",
	gamemodeConfig_ChatCommandPrefixName = "Prefix Du Chat",
	gamemodeConfig_ChatCommandPrefixDesc = "Préfix pour les commandes de chat",
	gamemodeConfig_RemovePropsName = "Retirer Les Props",
	gamemodeConfig_RemovePropsDesc = "Retirer tout les props de la map quand un le démarre et lors d'un cleanup.",
	gamemodeConfig_SpawnProtectionName = "Protection D'apparition",
	gamemodeConfig_SpawnProtectionDesc = "La duré d'invincibilité d'un joueur lorsqu'il apparait en seconde, mettre à -1 pour aucune protection.",
	gamemodeConfig_AFKTimeName = "AFK",
	gamemodeConfig_AFKTimeDesc = "Après combien de temps un joueur est considéré AFK. [En seconde]",
	gamemodeConfig_AllowPuntName = "Gravity Gun Punt",
	gamemodeConfig_AllowPuntDesc = "Activer/Désactiver le punt avec le Gravity Gun.",
	gamemodeConfig_WeaponBoxRemoveTimeName = "Boite D'arme",
	gamemodeConfig_WeaponBoxRemoveTimeDesc = "Àpres combien de temps un boite d'arme devrait disparaître. [En seconde]",
	gamemodeConfig_StartMoneyName = "Première Connexion",
	gamemodeConfig_StartMoneyDesc = "Avec combien d'argent les joueurs commence lors de leur première connexion au serveur.",
	gamemodeConfig_MaxLevelName = "Niveau Maximum",
	gamemodeConfig_MaxLevelDesc = "Le niveau maximum qu'un joueur peut avoir. [Maximum du jeu: 2,147,483,647]",
	gamemodeConfig_XPMultName = "Multiplicateur D'exp",
	gamemodeConfig_XPMultDesc = "Multiplicateur de l'exp recu sur le serveur. [1 = 100% // 2 = 200% // .5 = 50%]",
	gamemodeConfig_PhysGunExplosiveName = "Physics Gun Explosifs",
	gamemodeConfig_PhysGunExplosiveDesc = "Activer/Désactiver le fais de pouvoir prendre les explosif avec le Physics Gun.",
	gamemodeConfig_MinPropHPName = "Vie Minimum Props",
	gamemodeConfig_MinPropHPDesc = "La vie minimum d'un prop.",
	gamemodeConfig_MaxPropHPName = "Vie Maximum Props",
	gamemodeConfig_MaxPropHPDesc = "La vie Maximum d'un prop.",
	gamemodeConfig_DispenserCooldownName = "Distributeur",
	gamemodeConfig_DispenserCooldownDesc = "Le temps en chaque action d'un distributeur en second. [Peut être un chiffre à virgule]",
	gamemodeConfig_DefaultLimitName = "Limite Par Défaut",
	gamemodeConfig_DefaultLimitDesc = "La limite par défaut des objet dans le BaseWars Shop (F4).",
	gamemodeConfig_EntityRenderDistanceName = "Distance De Rendu",
	gamemodeConfig_EntityRenderDistanceDesc = "Jusqu'à quel distance un joueur peut voir l'interface d'une imprimante.",
	gamemodeConfig_BackMoneyName = "Argent Retour",
	gamemodeConfig_BackMoneyDesc = "L'argent qu'un joueur reçois lorsqu'il vent l'une de ses entitées en pourcentage. [1 = 100% // 2 = 200% // .5 = 50%]",
	gamemodeConfig_RaidImmunityName = "Immunitée De Raid",
	gamemodeConfig_RaidImmunityDesc = "Combien de temps un joueur/faction ne peut pas être raid. [En seconde]",
	gamemodeConfig_GlobalImmunityName = "Immunitée Global",
	gamemodeConfig_GlobalImmunityDesc = "La duré pendant lequel PERSONNE ne peut se faire raid. [En seconde]",
	gamemodeConfig_FactionLimitName = "Limite De Faction",
	gamemodeConfig_FactionLimitDesc = "Combien de joueur peut comprendre une faction au maximum (Incluant le chef).",
	gamemodeConfig_DestroyReturnName = "Argent Détruit",
	gamemodeConfig_DestroyReturnDesc = "L'argent qu'un joueur reçois quand il détruit une entitée en pourcentage. [1 = 100% // 2 = 200% // .5 = 50%]",
	gamemodeConfig_MaxBountyName = "Prime",
	gamemodeConfig_MaxBountyDesc = "Le maximum qu'un joueur peut mettre en prime sur quelqu'un. [/bounty]",
	gamemodeConfig_MaxPayName = "Paye",
	gamemodeConfig_MaxPayDesc = "Le maximum qu'un joueur peut donner à un autre joueur. [/pay]",
	gamemodeConfig_RespawnTimeName = "Temps De Réapparition",
	gamemodeConfig_RespawnTimeDesc = "Combien de temps avant qu'un joueur soit réapparu par le gamemode. [En seconde]",
	gamemodeConfig_DefaultLanguageName = "Langue",
	gamemodeConfig_DefaultLanguageDesc = "La langue par défaut quand un joueur rejoint le serveur pour la première fois. [Disponible: fr // en]",
	gamemodeConfig_SuperAdminSpawnPropsName = "Superadmin Props",
	gamemodeConfig_SuperAdminSpawnPropsDesc = "Activer/Désactiver le fait que les superadmin peuvent faire apparaitre n'importe quel prop.",
	gamemodeConfig_VIPName = "VIP",
	gamemodeConfig_VIPDesc = "Les grades VIP.",
	gamemodeConfig_AdminsName = "Administrateurs",
	gamemodeConfig_AdminsDesc = "Les grades administrateur.",
	gamemodeConfig_SuperAdminsName = "Superadmins",
	gamemodeConfig_SuperAdminsDesc = "Les grades superadmin. [Seul les personne avec ces grades peuvent accéder à ce menu donc faites attention!!!]",
	gamemodeConfig_PrinterCapName = "Limite D'imprimate",
	gamemodeConfig_PrinterCapDesc = "La limite d'imprimante par grades.",
	gamemodeConfig_PrinterMaxLevelName = "Niveau D'imprimante",
	gamemodeConfig_PrinterMaxLevelDesc = "Le niveau maximum d'une imprimante.",
	gamemodeConfig_PrinterMaxLevel = {
		intervalName = "Vitesse",
		intervalDesc = "La vitesse entre chaque impréssion d'une imprimante. [-0.05 seconde par niveau]",
		amountName = "Quantité",
		amountDesc = "La quantité d'argent une imprimante imprime.",
		capacityName = "Capacité",
		capacityDesc = "La capacité de l'imprimante.",
		paperCapacityName = "Capacité Papier",
		paperCapacityDesc = "La capacité de papier de l'imprimante.",
	},
	gamemodeConfig_PayDayName = "Jour De paye",
	gamemodeConfig_PayDayDesc = "Les information par rapport au module de paye.",
	gamemodeConfig_PayDay = {
		VIPName = "VIP",
		VIPDesc = "La quantité d'argent qu'un joueur (VIP & Admins) recois pour sa paye. [.1 » 10% de l'argent du joueur]",
		DefaultName = "Non VIP",
		DefaultDesc = "La quantité d'argent qu'un joueur (Non VIP) recois pour sa paye. [.025 » 2.5% de l'argent du joueur].",
		TimeName = "Jour De Paye",
		TimeDesc = "Les joueurs se font payé tout les combien de temps. [En seconde]",
		AFKPaydayName = "Paye AFK",
		AFKPaydayDesc = "Activer/Désactiver le fait qu'un joueur reçoit sa paye quand il est AFK.",
	},
	gamemodeConfig_RaidRequirementsName = "Condition De Raid",
	gamemodeConfig_RaidRequirementsDesc = "Les condition pour lancer un raid.",
	gamemodeConfig_RaidRequirements = {
		FactionName = "Raid En Faction",
		FactionDesc = "Combien d'imprimante une faction à besoin pour se faire raid/raid une autre faction.",
		SoloName = "Raid Seul",
		SoloDesc = "Combien d'imprimante un joueur à besoin pour se faire raid/raid un autre joueur",
	},
	gamemodeConfig_PhysgunPickupBlockedName = "Physics Gun Bloqué",
	gamemodeConfig_PhysgunPickupBlockedDesc = "Les entitées que le Physics Gun ne peut pas interagir avec.",
	gamemodeConfig_SpawnWeapsName = "Arme D'apparition",
	gamemodeConfig_SpawnWeapsDesc = "Les armes avec lesquels TOUT les joueurs apparaissent avec.",
	gamemodeConfig_WeaponDropBlacklistName = "Arme Blacklist",
	gamemodeConfig_WeaponDropBlacklistDesc = "Les armes qui ne peuvent pas être droppé.",
	gamemodeConfig_CategoryBlackListName = "Catégorie Blacklist",
	gamemodeConfig_CategoryBlackListDesc = "Les catégories d'armes qui ne peuvent pas être droppé.",
	gamemodeConfig_BlockedToolsName = "Outil Blacklist",
	gamemodeConfig_BlockedToolsDesc = "Tout les outils qui sont blacklist.",
	gamemodeConfig_FormatNumberName = "Formater Les Nombre",
	gamemodeConfig_FormatNumberDesc = "Comment les nombre sont formaté.",
	gamemodeConfig_WhitelistPropsName = "Props Whitelist",
	gamemodeConfig_WhitelistPropsDesc = "La liste de props que les joueurs peuvent faire apparaitre dans l'onglet \"Props\" du spawnmenu.",
	gamemodeConfig_DefaultHealthName = "Vie Par Defaut",
	gamemodeConfig_DefaultHealthDesc = "La quantité de santé par défaut avec laquelle un joueur apparaît.",
	gamemodeConfig_DefaultArmorName = "Armure Par Defaut",
	gamemodeConfig_DefaultArmorDesc = "La quantité d'armure par défaut avec laquelle un joueur apparaît.",
	gamemodeConfig_GiveWeaponOnBuyName = "Acheter Une Arme",
	gamemodeConfig_GiveWeaponOnBuyDesc = "Donner l'arme qu'un joueur achete directement au joueur au lieu de faire apparaitre l'arme au sol.",
	gamemodeConfig_FactionCollisionName = "Collision De Faction",
	gamemodeConfig_FactionCollisionDesc = "Activer/Désactiver le fait que les joueurs peuvent passer au travers des membres de leur faction.",
	gamemodeConfig_ShutdownRefundName = "Remboursement À La Fermeture",
	gamemodeConfig_ShutdownRefundDesc = "Rembourser tout les joueurs a la fermeture du serveur.",
	gamemodeConfig_AdminIsVIPName = "Admin VIP",
	gamemodeConfig_AdminIsVIPDesc = "Les groupes «admin» sont considérés comme des VIP (Pour les printers VIP par exemple).",
	gamemodeConfig_BankMaxLevelName = "Niveau De Banque",
	gamemodeConfig_BankMaxLevelDesc = "Le niveau maximum d'une banque.",
	gamemodeConfig_BankMaxLevel = {
		capacityName = "Capacité",
		capacityDesc = "La capacité de la banque.",
		healthName = "Vie",
		healthDesc = "La vie de la banque.",
	},
	gamemodeConfig_BombsOpenDoorsName = "Bombes",
	gamemodeConfig_BombsOpenDoorsDesc = "Les bombes ouvre les portes lors de leur explosion.",
	gamemodeConfog_MaxProfilesName = "Profils Max",
	gamemodeConfog_MaxProfilesDesc = "Le nombre maximum de profils qu'un joueur peut avoir.",
	gamemodeConfig_AdminsSpawnPropsName = "Admins Props",
	gamemodeConfig_AdminsSpawnPropsDesc = "Activer/Désactiver le fait que les admins peuvent faire apparaitre n'importe quel prop.",
	gamemodeConfig_MaxProfilesName = "Profils Maximum",
	gamemodeConfig_MaxProfilesDesc = "Nombre de profils qu'un joueur peut avoir.",
	gamemodeConfig_ServerOwnerName = "Fondateurs",
	gamemodeConfig_ServerOwnerDesc = "Les fondateurs du server, si votre steamid64 est ici, BaseWars:IsAdmin() et BaseWars:IsSuperAdmin(), vont toujours retourner «true»",
	gamemodeConfig_RaidsName = "Raids",
	gamemodeConfig_RaidsDesc = "Configuration des raids",
	gamemodeConfig_Raids = {
		minimumLevelName = "Niveau minimum",
		minimumLevelDesc = "Le niveau minimum pour lancer un raid et/ou se faire raider",
		durationName = "Durée",
		durationDesc = "La durée d'un raid",
		immunityName = "Immunité",
		immunityDesc = "L'immunité d'une personne/faction après s'être fait raider pendant laquelle personne ne pourra les raider",
		globalImmunityName = "Immunité globale",
		globalImmunityDesc = "L'immunité globale pendant laquelle personne ne pourra lancer de raid",
		shootPeopleInRaidName = "Tuer les personnes en raid",
		shootPeopleInRaidDesc = "Activer/Désactiver le fait de pouvoir tuer une personne qui est en raid alors que vous ne l'êtes pas vous-même",
		cancelOnDisconnectName = "Déconnexion",
		cancelOnDisconnectDesc = "Annuler un raid lorsqu'une personne qui était en raid se déconnecte"
	},
	gamemodeConfig_SpawnSafeZoneName = "Safe Zone",
	gamemodeConfig_SpawnSafeZoneDesc = "Configurez la safe zone",
	gamemodeConfig_SpawnSafeZone = {
		EnableName = "Activer",
		EnableDesc = "Activer/Désactiver la safe zone",
		PointAName = "Point A",
		PointADesc = "T'es stupid?",
		PointBName = "Point B",
		PointBDesc = "T'es stupid?",
	},
	gamemodeConfig_DamagableWhiteListName = "Endommageable par tous",
	gamemodeConfig_DamagableWhiteListDesc = "La liste des entités pouvant être endommagées par tout le monde à tout moment"
}

BaseWars.LANG["en"] = {
	languageName = "English",
	selectPlayer = "Select a player",

	shop_title = "BaseWars Shop",

















	error = "Error",
	close = "Close",
	notAllowed = "You do not have permission to do this",
	reloadThemes = "You have reloaded your themes.",
	choosePlayer = "Choose player:",
	amount = "Amount",
	targetNotFound = "The target was not found",
	invalidArguments = "Invalid argument",
	invalidArgumentNumber = "Invalid argument, needs a number",
	unlockalldoor = "All doors have been unlocked.",
	yes = "Yes",
	no = "No",
	none = "None",
	search = "Search",
	add = "Add",
	never = "Never",
	notYours = "That is not yours",
	all = "All",
	cancel = "Cancel",
	back = "Back",
	now = "Now",
	reset = "Reset",
	favorites = "Favorites",

	-- Misc?
	announcement_title = "Announcement - %s",
	levels_takeToLong = "Crash prevention, %s took a lot of XP.",
	spawnmenu_reloaded = "The spawnmenu has been reloaded",
	boughtCredits = "You have received your %s credits!",

	calculator_selectPrinter = "Select a printer",
	calculator_priceToUpgrade = "Price to upgrade: %s",
	calculator_printerProduction = "Production: %s",
	calculator_calculate = "Calculate",
	calculator_printerUpgrades = "Printer upgrades",
	calculator_prestigeUpgrades = "Prestige Upgrades",

	-- Player Lookup (Admin menu)
	playerlookup_search = "Search with SteamID or SteamID64",
	playerlookup_page = "Page %s/%s",
	playerlookup_prevPage = "Previous Page",
	playerlookup_nextPage = "Next Page",
	playerlookup_lastSeen = "Last Seen: %s",
	playerlookup_joined = "First Connection: %s",
	playerlookup_playerNoData = "This player has no data",
	playerlookup_bounty = "Bounty: %s (Stack » %s)",
	playerlookup_noProfileData = "No profile #%s",
	playerlookup_kills = "Kills: %s",
	playerlookup_deaths = "Deaths: %s",
	playerlookup_messageSent = "Messages sent: %s",
	playerlookup_playCount = "Play count: %s",
	playerlookup_moneyTaken = "Total money: %s",
	playerlookup_xpReceived = "Total XP: %s",
	playerlookup_neverConnected = "This player never connected to the server",

	-- Profile Selector
	profileSelector_profileNumber = "Profile #%s",
	profileSelector_money = "Money:",
	profileSelector_level = "Level:",
	profileSelector_xp = "XP:",
	profileSelector_timePlayed = "Time Played:",
	profileSelector_prestige = "Prestige:",
	profileSelector_profileID = "ProfileID:",
	profileSelector_play = "Play",
	profileSelector_creatingProfile = "Creating the profile...",
	profileSelector_wait = "Try again in %s seconds",
	profileSelector_waitingForData = "Waiting for profiles data",
	profileSelector_applyingProfile = "Please wait while your data is being applied",


	-- Context Menu
	contextmenu_game = "GAME INTERACTIONS",
	contextmenu_basewars = "BASEWARS INTERACTIONS",
	contextmenu_links = "IMPORTANT LINKS",
	contextmenu_callAdmin = "Call An Admin",
	contextmenu_clearDecals = "Clear Decals",
	contextmenu_stopSound = "Stop Sounds",
	contextmenu_adminMenu = "Admin Menu",
	contextmenu_cleanup = "Clean Up",
	contextmenu_respawn = "Respawn",
	contextmenu_doClearDecals = "Cleared Decals",
	contextmenu_doStopSound = "Stopped All Sounds",
	contextmenu_faction = "Factions",
	contextmenu_sellMenu = "Sell Menu",
	contextmenu_prestige = "Prestige",
	contextmenu_warnings = "Warnings",
	contextmenu_config = "Configuration",
	contextmenu_describeProblem = "Describe your problem in a few words",
	contextmenu_adminCalled = "You called an admin for \"%s\"",
	contextmenu_pendingTickets = "PENDING TICKETS",
	contextmenu_receivedTicket = "You receive a ticket",
	contextmenu_alreadyClaimed = "Already Claimed",
	contextmenu_claim = "Claim Ticket",
	contextmenu_tp = "TP",
	contextmenu_goto = "GOTO",
	contextmenu_closeTicket = "Your Ticket has been closed",
	contextmenu_playerLeft = "The player left the game",
	contextmenu_from = "From: %s",

	-- Admin Menu
	adminmenu_warnings = "Warnings",
	adminmenu_bans = "Bans",
	adminmenu_playerLookup  = "Players",
	adminmenu_logs = "Logs",
	adminmenu_factionLeader = "Faction Leader: %s",
	adminmenu_factionImmunity = "Faction Immunity: %s",
	adminmenu_factionMembers = "Faction Members:",
	adminmenu_disband = "Disband",
	adminmenu_changeLeader = "Change Leader",
	adminmenu_reset = "Reset",
	adminmenu_kick = "Kick",
	adminmenu_noLongerLeader = "You are no longer the leader of your faction",
	adminmenu_doResetImmunity = "You have reset the immunity of %s",
	adminmenu_doDisband = "You have disbanded the faction \"%s\"",
	adminmenu_changedLeader = "%s is now the leader of \"%s\"",
	adminmenu_beenKicked = "You have been kicked from your faction",
	adminmenu_kicked = "You have kicked %s from the faction",
	adminmenu_immunityReset = "Your immunity has been reset",
	adminmenu_resetGlobalImmunity = "The global immunity has been reset by %s",
	adminmenu_globalImmunity = "Global Immunity: %s",

	-- Leaderboard
	leaderboard_title = {
		time_played = "Time Played",
		money = "Richest Players",
		prestige = "Highest Prestige",
		level = "Highest Level",
		kills = "Number of Kills",
		deaths = "Number of Deaths",
		message_sent = "Messages Sent",
		money_received = "Total Money Received",
		xp_received = "Total XP Received",
		session_count = "Number of Sessions",
		kd = "Highest KD"
	},

	-- Dashboard
	dashboard_bounties = "Bounties",
	dashboard_staffOnline = "Staff Online",
	dashboard_AllCommands = "All The Commands",
	dashboard_copiedCommand = "Command copied",
	dashboard_commandExecuted = "You executed the command \"%s\"",
	dashboard_noStaffOnline = "No staff online",
	dashboard_noBounties = "No bounties",

	-- Death Notices
	deathNotice_suicide = "%s has committed suicide",
	deathNotice_noAttacker = "%s died due to %s",
	deathNotice_by = "%s killed %s with %s",
	deathNotice_fallDamage = "%s died of fall damage",

	-- SafeZone
	safeZone_spawnProp = "You cannot spawn props in the safe zone",
	safeZone_buy = "You cannot buy items in the safe zone.",
	safeZone_dropWeapon = "You cannot drop weapons in the safe zone.",

	-- Blocked Zone
	blockedZone_cantGoThere = "You cannot go there.",

	-- Context Menu (C)
	contextmenu_disable = "The context menu is disabled at the moment",

	-- Checkbox
	checkbox_on = "ON",
	checkbox_off = "OFF",

	-- Payday
	payday = "Payday, you receive %s",
	paydayAFK = "You cannot receive your payday while you are AFK",

	-- HUD
	hud_level = "Lvl: ",
	hud_spawnprotection = "You are invincible",
	hud_afkFor = "You have been AFK for %s",
	hud_armed = "Armed",
	hud_unarmed = "Unarmed",
	hud_youAreArmed = "You are armed",
	hud_youAreUnarmed = "You are not armed",

	-- Bounty Command
	bounty_title = "Bounty Menu",
	bounty_placeBounty = "Place a bounty of %s on the head of %s",
	bounty_receivedBounty = "%s has received %s for killing %s who had a bounty",
	bounty_placedOn = "%s has placed a bounty of %s on the head of %s",

	-- Bank
	bank_upgrade = "You have upgraded your bank for %s",
	bank_scan = "Scan",
	bank_doscan = "You have performed a scan, and found %s printers",
	bank_waitscan = "Waiting for the next scan (%ss)",
	bank_connectedMenu = "%s printers connected",
	bank_buyupgrade = "You have purchased the \"%s\" upgrade for %s",
	bank_notYours = "This bank is not yours.",
	bank_upgrades = {
		capacityName = "Capacity",
		capacityDesc = "Increases the bank's capacity.",
		healthName = "Health",
		healthDesc = "Increases the bank's health.",
	},

	-- Pay Command
	pay_title = "Pay Menu",
	pay_giveTo = "Give %s to %s",
	pay_payedPlayer = "You have given %s to %s",
	pay_payedBy = "%s has given you %s",
	pay_noOneToPay = "Do you want to give money to a ghost???",
	pay_cantPayBot = "You cannot give money to a bot",

	-- Sell Menu
	sellmenu_allEntities = "All entities",
	sellmenu_selectedEntities = "Selected entities",
	sellmenu_sellallfor = "Sell everything for %s",
	sellmenu_sellselectedfor = "Sell the selection for %s",
	sellmenu_sellDuringRaid = "You cannot sell while you are in a raid",
	sellmenu_sell = "You have sold %s entities for %s",
	sellmenu_sellTitle = "Selling",
	sellmenu_sellallText = "Sell %s entities for %s",
	sellmenu_sellButton = "Sell",

	-- BaseWars Menu (F3)
	bwm_dashboard = "Dashboard",
	bwm_leaderboard = "Leaderboard",
	bwm_faction = "Faction",
	bwm_raid = "Raid",
	bwm_sellmenu = "Selling",
	bwm_logs = "Logs",
	bwm_prestige = "Prestige",
	bwm_config = "Configuration",
	bwm_notificationsHistory = "Notifs History",

	-- Spawnpoint
	spawnpoint_nametitle = "Change name",
	spawnpoint_name = "Name (Between 3 and 32 characters)",
	spawnpoint_setname = "Set the name \"%s\" for this spawn point",
	spawnpoint_chose = "Choose your spawn",
	spawnpoint_tooshort = "The spawn point name is too short",
	spawnpoint_toolong = "The spawn point name is too long",
	spawnpoint_howto = "Press \"%s\" to change the name",
	spawnpoint_currentname = "Name: %s",
	spawnpoint_notyours = "This spawn point is not yours",
	spawnpoint_choosebefore = "Choose a spawn point",
	spawnpoint_spawnatworld = "Respawn at the world spawn",

	-- Scoreboard
	scoreboard_goBack = "Back",
	scoreboard_rank = "Rank: %s",
	scoreboard_faction = "Faction: %s",
	scoreboard_factionLeader = "Faction Leader: %s",
	scoreboard_money = "Money: %s",
	scoreboard_level = "Level: %s",
	scoreboard_prestige = "Prestige: %s",
	scoreboard_hp = "Health: %s/%s",
	scoreboard_armor = "Armor: %s/%s",
	scoreboard_xp = "XP: %s/%s",
	scoreboard_kd = "K/D: %s/%s (%s)",
	scoreboard_ping = "Ping: %s",
	scoreboard_bounty = "Bounty: %s",
	scoreboard_afk = "AFK: %s",
	scoreboard_god = "God: %s",
	scoreboard_cloak = "Cloak: %s",
	scoreboard_timeplay = "Playtime: %s",
	scoreboard_steamidCopied = "You copied the SteamID of %s",
	scoreboard_steamid64Copied = "You copied the SteamID64 of %s",
	scoreboard_nameCopied = "You copied the Name of %s",
	scoreboard_steamid = "SteamID: %s",
	scoreboard_steamid64 = "SteamID64: %s",
	scoreboard = {
		name = "USERNAME",
		level = "LEVEL",
		prestige = "PRESTIGE",
		kills = "KILLS",
		deaths = "DEATHS",
		ping = "PING",
	},

	-- Printer
	printer_takeMoney = "WITHDRAW MONEY",
	printer_takeMoneyButton = "WITHDRAW %s",
	printer_superAdminBypass = "SuperAdmin Bypass",
	printer_notYours = "This printer is not yours.",
	printer_upgradeOnce = "UPGRADE ONCE FOR %s",
	printer_upgradeMax = "UPGRADE %sx FOR %s",
	printer_maxupgrade = "This upgrade can no longer be purchased",
	printer_cantafford = "You do not have enough to afford this",
	printer_buyupgrade = "You have purchased the \"%s\" upgrade %s times for %s",
	printer_cantAffordUpgrade = "You don't have enough money to buy this upgrade.",
	printer_VIPOnly = "VIP ONLY",
	printer_upgrade = "Upgrade",
	printer_buypaper = "Buy Paper",
	printer_buyPaperMenu = "BUY PAPER",
	printer_buyPaperFor = "BUY %s PAPER FOR %s",
	printer_full = "PRINTER FULL",
	printer_bank_full = "BANK FULL",
	printer_xp = "XP: %s",
	printer_paper = "Paper: %s/%s",
	printer_time = "Time remaining: %s",
	printer_connectedToBank = "Connected to a bank",
	printer_noPrinterConnected = "No printer connected",
	printer_maxed = "MAX",
	printer_printOutOfPaper = "Printers Out Of Paper",
	printer_quickUpgrade = "QUICK UPGRADE",
	printer_upgradeMenu = "UPGRADE",
	printer_level = "LEVEL",
	printer_price = "PRICE",
	printer_tooExpensive = "TOO EXPENSIVE",
	printer_upgrades = {
		intervalName = "Speed",
		intervalDesc = "Increases the printer's speed. Reduces printing time by 0.05 seconds per upgrade.",
		amountName = "Value",
		amountDesc = "Increases the amount of money produced by the printer.",
		capacityName = "Capacity",
		capacityDesc = "Increases the printer's capacity.",
		paperCapacityName = "Paper Capacity",
		paperCapacityDesc = "Increases the printer's paper capacity.",
		autoPaperName = "Auto Paper",
		autoPaperDesc = "Automatically buys paper when the printer runs out.",
	},

	-- Commands
	command_setMoney_set = "You have set %s's money to %s",
	command_setMoney_setBy = "%s has set your money to %s",
	command_addMoney_add = "You gave %s to %s",
	command_addMoney_addBy = "%s gave you %s",
	command_setPointshop_set = "You have set %s's pointshop to %s",
	command_setPointshop_setBy = "%s has set your pointshop to %s",
	command_addPointshop_add = "You gave %s pointshop to %s",
	command_addPointshop_addBy = "%s gave you %s pointshop",
	command_setCredits_set = "You have set %s's credits to %s",
	command_setCredits_setBy = "%s has set your credits to %s",
	command_addCredits_add = "You gave %s credits to %s",
	command_addCredits_addBy = "%s gave you %s credits",
	command_setPrestige_set = "You have set %s's prestige to %s",
	command_setPrestige_setBy = "%s has set your prestige to %s",
	command_addPrestige_add = "You gave %s prestige to %s",
	command_addPrestige_addBy = "%s gave you %s prestige",
	command_setLevel_set = "You set %s's level to %s",
	command_setLevel_setBy = "%s set your level to %s",
	command_addLevel_add = "You gave %s levels to %s",
	command_addLevel_addBy = "%s gave you %s levels",
	command_setXP_set = "You set %s's XP to %s",
	command_setXP_setBy = "%s set your XP to %s",
	command_addXP_add = "You gave %s XP to %s",
	command_addXP_addBy = "%s gave you %s XP",
	command_refund_refundPlayer = "You fully refunded (%s)",
	command_refund_refundBy = "You were refunded by %s",
	command_bot_spawn = "%s spawned %s bots",
	command_bot_serverFull = "Server full",
	command_bot_kick = "You kicked all bots from the server",
	command_dropWeapon_blackilst = "This weapon is blacklisted and cannot be dropped",
	command_respawn_respawn = "You respawned %s",
	command_respawn_respawnBy = "%s respawned you",
	command_reset_resetPlayer = "You reset %s's stats",
	command_reset_resetBy = "Your stats were reset by %s",
	command_playerValue = "%s is valued at %s",
	command_raid_forceStopped = "A raid has been stop by %s (Admin)",
	command_raid_noRaid = "There is no raid going on",
	command_god = "Godmode ON",
	command_ungod = "Godmode OFF",
	command_cloak = "Cloak ON",
	command_uncloak = "Cloak OFF",
	commands_deactivated = "Command deactivated",
	commands_payTime = "Time until next payday: %s",
	command_clearNotifs = "You have deleted all your notifications",
	commands_wrongPrefix = "Wrong prefix, use the command \"%s\"",
	commands_commandDontExist = "The command \"%s\" don't exist",
	commands_allDataDeleted = "All your data have been deleted",
	commands_profileDataDeleted = "All your profiles have been deleted",
	commands_deleteProfilesDataOf = "You deleted profiles of %s",
	commands_deleteAllDataOf = "You deleted all data of %s",

	-- Raid
	raids_raidAlreadyGoingOn = "A raid is already on going",
	raids_globalImmunity = "You can't start a raid during global immunity (%s)",
	raids_raidYourself = "You can't raid yourself...",
	raids_raidSoloWhileInFaction = "You can't raid a person that is not in a faction if you are in one",
	raids_raidFactionWhileSolo = "You can't raid a person that is in a faction if you are not in one",
	raids_raidFactionMate = "You can't raid a person that is in your faction",
	raids_yourLevelTooLow = "Your level is too low (%s levels missing)",
	raids_opponentLevelTooLow = "Your opponent level is too low (%s levels missing)",
	raids_factionImmunity = "The faction \"%s\" still has its immunity (%s)",
	raids_playerImmunity = "The player \"%s\" still has their immunity (%s)",
	raids_raidStarted = "A raid started between \"%s\" and \"%s\" started by %s",
	raids_stopRaidWhenNoRaid = "There is no raid to stop",
	raids_stopRaidWhenNotInRaid = "You can't stop a raid if you are not part of it",
	raids_stopRaidWhenNotAttacker = "You can't stop a raid if you are not the attacker",
	raids_stopRaidWhenNotLeader = "You can't stop a raid if you are not the leader",
	raids_raidStopped = "The raid was cancel by %s",
	raids_canceledByAdmin = "The raid has been canceled by an admin",
	raids_finished = "The raid has ended",
	raids_cancelWhenPlayerDisconnect = "The raid was canceled because %s diconnected",
	raids_globalImmunity = "Global Immunity: %s",
	raids_resetGlobalImmunity = "The global immunity has been reset",
	raids_yourImmunity = "Your immunity has been reset",
	raids_youResetPlayerImmunity = "You have reset the immunity of %s",
	raids_playerImmunityAdmin = "%s immunity: %s",
	raids_cantShootPersonInRaid = "You can't shoot at people that are in a raid",
	raids_destroyEntity = "You have received %s for destroying \"%s\"",
	raids_buttons = {
		start = "Start a raid",
		stop = "Stop a raid"
	},

	-- Config
	config_number = "Number",
	config_vector_x = "X",
	config_vector_y = "Y",
	config_vector_z = "Z",
	config_string = "Text",
	config_playerConfig = "Player Configuration",
	config_gamemodeConfig = "Gamemode Configuration",
	f3config = {
		showHUDName = "Show HUD",
		showHUDDesc = "Show the HUD of the gamemode",
		autoPrestigeName = "Auto Prestige",
		autoPrestigeDesc = "Automatically prestige when you have the level",
		autoSellOnLeaveName = "Auto Sell",
		autoSellOnLeaveDesc = "Automatically sell your items when leaving the game.",
		bluredBackgroundName = "Blurred Background",
		bluredBackgroundDesc = "The F3/F4 menu background is blurred.",
		damageOwnEntitiesName = "Damage Entities",
		damageOwnEntitiesDesc = "Damage your own entities.",
		seeOtherPrinterName = "See Other Printers",
		seeOtherPrinterDesc = "See other players' printers interface.",
		seeYourPrinterName = "See Your Printers",
		seeYourPrinterDesc = "See your printers interface.",
		languageName = "Language",
		languageDesc = "Change the language.",
		themeName = "Theme",
		themeDesc = "Change the theme.",
		showBuyPopupName = "Buy Popup",
		showBuyPopupDesc = "Show a popup to confirm a purchase or reason for purchase failure in the purchase menu (%s).",
		closeOnBuyName = "Close After Purchase",
		closeOnBuyDesc = "Close the menu after a purchase in the purchase menu (%s).",
		showAdvertsName = "Adverts",
		showAdvertsDesc = "Show adverts in the chat.",
		hideNonBuyableName = "Hide Non-Buyable",
		hideNonBuyableDesc = "Hide all items that are not buyable in the purchase menu (%s).",
		hideEmptyCategoriesName = "Hide Empty Categories",
		hideEmptyCategoriesDesc = "Hide empty categories in the purchase menu (%s).",
		formatTimeDaysName = "Time Formating",
		formatTimeDaysDesc = "Format time in days [OFF: 65h 4m; ON: 2d 17h 4m]",
		factionHighlightName = "Faction Highlight",
		factionHighlightDesc = "Highlight the members of your faction",
		showAllCommandsName = "All the commands",
		showAllCommandsDesc = "Show the commands you don't have access in the dashboard",
		F4TabName = "BaseWars Shop Tab",
		F4TabDesc = "The tab on which the shop will open",
	},

	-- BaseWars Shop (F4)
	bws_level = "Level: %s",
	bws_limit = "Limit: %s",
	bws_prestige = "Prestige: %s",
	bws_cantLevel = "Requires level %s",
	bws_cantMoney = "Requires %s",
	bws_cantPrestige = "Requires prestige %s",
	bws_cantVIP = "Requires %s",
	bws_cantRaid = "Raid only",
	bws_buyItem = "You bought \"%s\" for %s",
	bws_cantBuyBomb = "You can only buy bombs during a raid",
	bws_cantBuyDuringRaid = "You cannot buy this during a raid",
	bws_printerCap = "You have reached your printer limit",
	bws_forWho = "You must be %s to buy this item",
	bws_tooExpensive = "You cannot afford this",
	bws_lowLevel = "Your level is too low to buy this",
	bws_reachLimit = "You have reached the limit of this item",
	bws_lowPrestige = "You are not a high enough prestige for this",
	bws_copyBind = "Bind for \"%s\" copied",
	bws_nothingToBuy = "There is nothing you can buy.",
	bws_confirm = "Confirm",
	bws_cancel = "Cancel",
	bws_understand = "I understand",
	bws_confirmPurchase = "Purchase Confirmation",
	bws_confirmError = "Purchase Error",
	bws_buyConfirm = "Buy \"%s\" for %s",
	bws_slowDown = "Too fast! (%ss)",
	bws_addFavorite = "You added \"%s\" to your favorites",
	bws_removeFavorite = "You removed \"%s\" from your favorites",
	bws_last = "Last Tab",

	-- Faction
	faction_factionName = "Faction Name",
	faction_password = "Password",
	faction_noFaction = "No Faction",
	faction_createFaction = "Create Faction",
	faction_create = "Create",
	faction_joinFaction = "Join Faction",
	faction_join = "Join",
	faction_quitFaction = "Quit Faction",
	faction_quit = "Quit",
	faction_changePassword = "Change Password",
	faction_change = "Change",
	faction_kickMember = "Kick Member",
	faction_kick = "Kick",
	faction_promoteLeader = "Promote Leader",
	faction_promote = "Promote",
	faction_frendlyFire = "Frendly Fire",
	faction_createdFaction = "You have created the faction \"%s\"",
	faction_alreadyInFaction = "You are already in a faction",
	faction_nameTaken = "The faction \"%s\" already exists",
	faction_nameTooShort = "Faction name is too short",
	faction_dontExist = "The faction \"%s\" doesn't exist",
	faction_reachMemberLimit = "This faction has reached the maximum number of members (%s)",
	faction_wrongPassword = "Wrong password",
	faction_playerJoinFaction = "You have joined the faction \"%s\"",
	faction_playerJoinYourFaction = "%s has joined your faction",
	faction_notInFaction = "You must be in a faction",
	faction_kickDisband = "You have been kicked from the faction because it was disbanded",
	faction_disband = "You have left the faction",
	faction_notLeader = "You are not the leader of the faction",
	faction_passwordChanged = "You have changed the password from \"%s\" to \"%s\"",
	faction_cantDoToYourself = "You can't do this to yourself",
	faction_differentFaction = "You are not in the same faction",
	faction_notMemberOfYourFaction = "%s is not a member of your faction",
	faction_kickedPlayer = "You have kicked %s from the faction",
	faction_kicked = "You have been kicked from the faction",
	faction_promotedLeader = "You have promoted %s to be the leader of the faction",
	faction_becameLeader = "You have become the leader of the faction",
	faction_leaderDisconnected = "You have been kicked from the faction because the leader disconnected",
	faction_passwordTooLong = "Password is too long",
	faction_nameTooLong = "Faction name is too long",
	faction_inRaid = "You can't do that while in a raid",
	faction_changedFrendlyFire = "Friendly Fire: %s",
	faction_nameBlocked = "You can't create a faction with the name \"%s\"",
	faction_cantJoinDuringRaid = "You can't join a faction that is in a raid",
	faction_changedFrendlyFireAdmin = "You have changed the friendly fire of \"%s\" to: %s",

	-- Gamemode Config
	gamemodeConfig_updated = "The gamemode configuration has been updated.",
	gamemodeConfig_shortText = "Txt",
	gamemodeConfig_remove = "Remove",
	gamemodeConfig_userGroup = "Rank",
	gamemodeConfig_weaponClass = "Weapon Class",
	gamemodeConfig_entityClass = "Entity Class",
	gamemodeConfig_tool = "Tool",
	gamemodeConfig_category = "Category",
	gamemodeConfig_model = "Model",
	gamemodeConfig_steamID64 = "SteamID64",
	gamemodeConfig_saveConfig = "Save",
	gamemodeConfig_resetConfig = "Reset",
	gamemodeConfig_PrinterPublicName = "Public Printer",
	gamemodeConfig_PrinterPublicDesc = "When disabled, only the owner of a printer can interact with it.",
	gamemodeConfig_PrinterPaperPriceName = "Paper Price",
	gamemodeConfig_PrinterPaperPriceDesc = "The price of a single paper.",
	gamemodeConfig_SBoxWeapsName = "Sandbox Weapons",
	gamemodeConfig_SBoxWeapsDesc = "Players spawn with HL2 weapons.",
	gamemodeConfig_NotifyAllWhenConfigModifiedName = "Notify Everyone",
	gamemodeConfig_NotifyAllWhenConfigModifiedDesc = "Notify everyone when an administrator modifies the gamemode configuration.",
	gamemodeConfig_BankRadiusName = "Bank Distance",
	gamemodeConfig_BankRadiusDesc = "The distance at which a bank can detect a printer, set to 0 for infinite range.",
	gamemodeConfig_WalkSpeedName = "Walk Speed",
	gamemodeConfig_WalkSpeedDesc = "The speed at which a player walks.",
	gamemodeConfig_RunSpeedName = "Run Speed",
	gamemodeConfig_RunSpeedDesc = "The speed at which a player runs.",
	gamemodeConfig_ChatCommandPrefixName = "Chat Prefix",
	gamemodeConfig_ChatCommandPrefixDesc = "Prefix for chat commands.",
	gamemodeConfig_RemovePropsName = "Remove Props",
	gamemodeConfig_RemovePropsDesc = "Remove all props from the map when the gamemode starts and during a cleanup.",
	gamemodeConfig_SpawnProtectionName = "Spawn Protection",
	gamemodeConfig_SpawnProtectionDesc = "The duration of a player's spawn invincibility in seconds, set to -1 for no protection.",
	gamemodeConfig_AFKTimeName = "AFK Time",
	gamemodeConfig_AFKTimeDesc = "After how much time a player is considered AFK. [In seconds]",
	gamemodeConfig_AllowPuntName = "Gravity Gun Punt",
	gamemodeConfig_AllowPuntDesc = "Enable/Disable punting with the Gravity Gun.",
	gamemodeConfig_WeaponBoxRemoveTimeName = "Weapon Box",
	gamemodeConfig_WeaponBoxRemoveTimeDesc = "After how much time a weapon box should disappear. [In seconds]",
	gamemodeConfig_StartMoneyName = "Initial Money",
	gamemodeConfig_StartMoneyDesc = "How much money players start with on their first connection to the server.",
	gamemodeConfig_MaxLevelName = "Maximum Level",
	gamemodeConfig_MaxLevelDesc = "The maximum level a player can reach. [Game's maximum: 2,147,483,647]",
	gamemodeConfig_XPMultName = "XP Multiplier",
	gamemodeConfig_XPMultDesc = "Multiplier for the experience received on the server. [1 = 100% // 2 = 200% // .5 = 50%]",
	gamemodeConfig_PhysGunExplosiveName = "Physics Gun Explosives",
	gamemodeConfig_PhysGunExplosiveDesc = "Enable/Disable the ability to pick up explosives with the Physics Gun.",
	gamemodeConfig_MinPropHPName = "Minimum Prop HP",
	gamemodeConfig_MinPropHPDesc = "The minimum HP of a prop.",
	gamemodeConfig_MaxPropHPName = "Maximum Prop HP",
	gamemodeConfig_MaxPropHPDesc = "The maximum HP of a prop.",
	gamemodeConfig_DispenserCooldownName = "Dispenser Cooldown",
	gamemodeConfig_DispenserCooldownDesc = "The time between each action of a dispenser in seconds. [Can be a decimal number]",
	gamemodeConfig_DefaultLimitName = "Default Limit",
	gamemodeConfig_DefaultLimitDesc = "The default limit of items in the BaseWars Shop (F4).",
	gamemodeConfig_EntityRenderDistanceName = "Render Distance",
	gamemodeConfig_EntityRenderDistanceDesc = "How far a player can see the interface of a printer.",
	gamemodeConfig_BackMoneyName = "Returned Money",
	gamemodeConfig_BackMoneyDesc = "The money a player receives when selling one of their entities as a percentage. [1 = 100% // 2 = 200% // .5 = 50%]",
	gamemodeConfig_RaidImmunityName = "Raid Immunity",
	gamemodeConfig_RaidImmunityDesc = "How long a player/faction cannot be raided. [In seconds]",
	gamemodeConfig_GlobalImmunityName = "Global Immunity",
	gamemodeConfig_GlobalImmunityDesc = "The duration during which NO ONE can be raided. [In seconds]",
	gamemodeConfig_FactionLimitName = "Faction Limit",
	gamemodeConfig_FactionLimitDesc = "How many players can be in a faction at maximum (including the leader).",
	gamemodeConfig_DestroyReturnName = "Destroyed Money",
	gamemodeConfig_DestroyReturnDesc = "The money a player receives when destroying an entity as a percentage. [1 = 100% // 2 = 200% // .5 = 50%]",
	gamemodeConfig_MaxBountyName = "Bounty",
	gamemodeConfig_MaxBountyDesc = "The maximum bounty a player can place on someone. [/bounty]",
	gamemodeConfig_MaxPayName = "Pay",
	gamemodeConfig_MaxPayDesc = "The maximum a player can give to another player. [/pay]",
	gamemodeConfig_RespawnTimeName = "Respawn Time",
	gamemodeConfig_RespawnTimeDesc = "How much time before a player respawns by the gamemode. [In seconds]",
	gamemodeConfig_DefaultLanguageName = "Language",
	gamemodeConfig_DefaultLanguageDesc = "The default language when a player joins the server for the first time. [Available: fr // en]",
	gamemodeConfig_SuperAdminSpawnPropsName = "Superadmin Props",
	gamemodeConfig_SuperAdminSpawnPropsDesc = "Enable/Disable superadmins being able to spawn any prop.",
	gamemodeConfig_VIPName = "VIP",
	gamemodeConfig_VIPDesc = "VIP ranks.",
	gamemodeConfig_AdminsName = "Administrators",
	gamemodeConfig_AdminsDesc = "Administrator ranks.",
	gamemodeConfig_SuperAdminsName = "Superadmins",
	gamemodeConfig_SuperAdminsDesc = "Superadmin ranks. [Only people with these ranks can access this menu, so be careful!]",
	gamemodeConfig_PrinterCapName = "Printer Limit",
	gamemodeConfig_PrinterCapDesc = "The printer limit per rank.",
	gamemodeConfig_PrinterMaxLevelName = "Printer Level",
	gamemodeConfig_PrinterMaxLevelDesc = "The maximum level of a printer.",
	gamemodeConfig_PrinterMaxLevel = {
		intervalName = "Speed",
		intervalDesc = "The speed between each printer's print. [-0.05 seconds per level]",
		amountName = "Amount",
		amountDesc = "The amount of money a printer prints.",
		capacityName = "Capacity",
		capacityDesc = "The capacity of a printer.",
		paperCapacityName = "Paper Capacity",
		paperCapacityDesc = "The paper capacity of a printer.",
	},
	gamemodeConfig_PayDayName = "Payday",
	gamemodeConfig_PayDayDesc = "Configuration the payday module.",
	gamemodeConfig_PayDay = {
		VIPName = "VIP",
		VIPDesc = "The amount of money a player (VIP & Admins) receives for their payday. [.1 » 10% of the player's money]",
		DefaultName = "Non VIP",
		DefaultDesc = "The amount of money a player (Non VIP) receives for their payday. [.025 » 2.5% of the player's money].",
		TimeName = "Payday Time",
		TimeDesc = "How often players get paid. [In seconds]",
		AFKPaydayName = "AFK Payday",
		AFKPaydayDesc = "Enable/Disable players receiving their payday while AFK.",
	},
	gamemodeConfig_RaidRequirementsName = "Raid Requirements",
	gamemodeConfig_RaidRequirementsDesc = "Conditions for initiating a raid.",
	gamemodeConfig_RaidRequirements = {
		FactionName = "Faction Raid",
		FactionDesc = "How many printers a faction needs to initiate/raid another faction.",
		SoloName = "Solo Raid",
		SoloDesc = "How many printers a player needs to initiate/raid another player.",
	},
	gamemodeConfig_PhysgunPickupBlockedName = "Blocked Physics Gun",
	gamemodeConfig_PhysgunPickupBlockedDesc = "Entities that the Physics Gun cannot interact with.",
	gamemodeConfig_SpawnWeapsName = "Spawn Weapons",
	gamemodeConfig_SpawnWeapsDesc = "The weapons ALL players spawn with.",
	gamemodeConfig_WeaponDropBlacklistName = "Weapon Blacklist",
	gamemodeConfig_WeaponDropBlacklistDesc = "Weapons that cannot be dropped.",
	gamemodeConfig_CategoryBlackListName = "Category Blacklist",
	gamemodeConfig_CategoryBlackListDesc = "Weapon categories that cannot be dropped.",
	gamemodeConfig_BlockedToolsName = "Tool Blacklist",
	gamemodeConfig_BlockedToolsDesc = "All the tools that are blacklisted.",
	gamemodeConfig_FormatNumberName = "Format Numbers",
	gamemodeConfig_FormatNumberDesc = "How numbers are formatted.",
	gamemodeConfig_WhitelistPropsName = "Props Whitelist",
	gamemodeConfig_WhitelistPropsDesc = "The list of props that players can spawn from the \"Props\" tab in the spawn menu.",
	gamemodeConfig_DefaultHealthName = "Default Health",
	gamemodeConfig_DefaultHealthDesc = "The default amount of health a player spawn with.",
	gamemodeConfig_DefaultArmorName = "Default Armor",
	gamemodeConfig_DefaultArmorDesc = "The default amount of armor a player spawn with",
	gamemodeConfig_GiveWeaponOnBuyName = "Buy A Weapon",
	gamemodeConfig_GiveWeaponOnBuyDesc = "Give the weapon a player buy to them directly instead of spawning it on the gorund.",
	gamemodeConfig_FactionCollisionName = "Faction Collision",
	gamemodeConfig_FactionCollisionDesc = "Can player go through their team mate or not.",
	gamemodeConfig_ShutdownRefundName = "Shutdown Refund",
	gamemodeConfig_ShutdownRefundDesc = "Refund everybody when the server shutdown.",
	gamemodeConfig_AdminIsVIPName = "Admin VIP",
	gamemodeConfig_AdminIsVIPDesc = "\"Admin\" groups are considered VIPs (For VIP printers for example).",
	gamemodeConfig_BankMaxLevelName = "Bank Level",
	gamemodeConfig_BankMaxLevelDesc = "The maximum level of a bank.",
	gamemodeConfig_BankMaxLevel = {
		capacityName = "Capacity",
		capacityDesc = "The capacity of a bank.",
		healthName = "Health",
		healthDesc = "The health of a bank.",
	},
	gamemodeConfig_BombsOpenDoorsName = "Bombs",
	gamemodeConfig_BombsOpenDoorsDesc = "Bombs open doors when they explode.",
	gamemodeConfog_MaxProfilesName = "Max Profiles",
	gamemodeConfog_MaxProfilesDesc = "The maximum amount of profiles a player can have.",
	gamemodeConfig_AdminsSpawnPropsName = "Admins Props",
	gamemodeConfig_AdminsSpawnPropsDesc = "Enable/Disable admins being able to spawn any prop.",
	gamemodeConfig_MaxProfilesName = "Maximum Profiles",
	gamemodeConfig_MaxProfilesDesc = "The amount of proilfes a player can have",
	gamemodeConfig_ServerOwnerName = "Owners",
	gamemodeConfig_ServerOwnerDesc = "The owners of the server, if your steamid64 is here you, BaseWars:IsAdmin() and BaseWars:IsSuperAdmin() will always return \"true\"",
	gamemodeConfig_RaidsName = "Raids",
	gamemodeConfig_RaidsDesc = "Raids Configuration",
	gamemodeConfig_Raids = {
		minimumLevelName = "Minimum Level",
		minimumLevelDesc = "The minimum level required to start a raid and/or be raided",
		durationName = "Duration",
		durationDesc = "The duration of a raid",
		immunityName = "Immunity",
		immunityDesc = "The immunity of a person/faction after being raided during which no one can raid them",
		globalImmunityName = "Global Immunity",
		globalImmunityDesc = "The global immunity during which no one can start a raid",
		shootPeopleInRaidName = "Kill People in Raid",
		shootPeopleInRaidDesc = "Enable/Disable the ability to kill a person who is in a raid while you are not",
		cancelOnDisconnectName = "Disconnection",
		cancelOnDisconnectDesc = "Cancel a raid when a person who was in a raid disconnects"
	},
	gamemodeConfig_SpawnSafeZoneName = "Safe Zone",
	gamemodeConfig_SpawnSafeZoneDesc = "Configure the safe zone if you have a spawn thats kinda fucked up or whatever other reason",
	gamemodeConfig_SpawnSafeZone = {
		EnableName = "Enable",
		EnableDesc = "Enable/Disable the safe zone",
		PointAName = "Point A",
		PointADesc = "Are you that dumb?",
		PointBName = "Point B",
		PointBDesc = "Are you that dumb?",
	},
	gamemodeConfig_DamagableWhiteListName = "Damagable By All",
	gamemodeConfig_DamagableWhiteListDesc = "The list of entities that can take damage by everyone at all time",
}

--[[-------------------------------------------------------------------------
DO NOT TOUCH
---------------------------------------------------------------------------]]
BaseWars.AllLang = {}
for k, v in pairs(BaseWars.LANG) do
	BaseWars.AllLang[k] = v.languageName
end
--[[-------------------------------------------------------------------------
DO NOT TOUCH
---------------------------------------------------------------------------]]