--[[
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
	DO NOT EDIT THIS FILE, THE CONFIGURATION OF THE GAMEMODE IS MADE IN GAME
]]

--[[-------------------------------------------------------------------------
	CONFIG TYPES
---------------------------------------------------------------------------]]
BWCONFIGTYPE_NONE = 0
BWCONFIGTYPE_KEY = 1
BWCONFIGTYPE_KEYVALUE = 2
BWCONFIGTYPE_NOKEY = 3

BaseWars.DefaultConfig = {}
BaseWars.DefaultConfigType = {
	["SpawnWeaps"] = BWCONFIGTYPE_NOKEY,
	["WhitelistProps"] = BWCONFIGTYPE_NOKEY,

	["PrinterMaxLevel"] = BWCONFIGTYPE_KEYVALUE,
	["BankMaxLevel"] = BWCONFIGTYPE_KEYVALUE,
	["RaidRequirements"] = BWCONFIGTYPE_KEYVALUE,
	["PayDay"] = BWCONFIGTYPE_KEYVALUE,
	["Raids"] = BWCONFIGTYPE_KEYVALUE,
	["AutoRestart"] = BWCONFIGTYPE_KEYVALUE,
	["CrashBackup"] = BWCONFIGTYPE_KEYVALUE,
	["Debug"] = BWCONFIGTYPE_KEYVALUE,

	["VIP"] = BWCONFIGTYPE_KEY,
	["Admins"] = BWCONFIGTYPE_KEY,
	["SuperAdmins"] = BWCONFIGTYPE_KEY,
	["WeaponDropBlacklist"] = BWCONFIGTYPE_KEY,
	["CategoryBlackList"] = BWCONFIGTYPE_KEY,
	["BlockedTools"] = BWCONFIGTYPE_KEY,
	["PhysgunPickupBlocked"] = BWCONFIGTYPE_KEY,
}

function BaseWars:AddDefaultConfig(configKey, configType, config, configTranslation)
	if not configKey then
		return
	end

	if BaseWars.DefaultConfig[configKey] != nil then
		BaseWars:Warning("Config \"" .. configKey .. "\" already exists!")
		return
	end

	if not config then
		BaseWars:Warning("Missing value for \"" .. configKey .. "\"")
		return
	end

	if istable(config) and (not configType or configType == 0) then
		BaseWars:Warning("Wrong type for \"" .. configKey .. "\"")
		return
	end

	BaseWars.DefaultConfig[configKey] = config

	-- I dont need that if its not a table
	if configType and configType > 0 then
		BaseWars.DefaultConfigType[configKey] = configType
	end

	if configTranslation and istable(configTranslation) then
		for languageCode, translations in pairs(configTranslation) do
			languageCode = string.lower(languageCode)

			for k, v in pairs(translations) do
				if k == "name" then
					BaseWars.LANG[languageCode]["gamemodeConfig_" .. configKey .. "Name"] = v
				end

				if k == "desc" then
					BaseWars.LANG[languageCode]["gamemodeConfig_" .. configKey .. "Desc"] = v
				end

				if k == "extra" and istable(v) then
					BaseWars.LANG[languageCode]["gamemodeConfig_" .. configKey] = {}

					for extraKey, extraValue in pairs(v) do
						BaseWars.LANG[languageCode]["gamemodeConfig_" .. configKey][extraKey .. "Name"] = extraValue.name
						BaseWars.LANG[languageCode]["gamemodeConfig_" .. configKey][extraKey .. "Desc"] = extraValue.desc
					end
				end
			end
		end
	end
end

--[[-------------------------------------------------------------------------
	DEFAULT CONFIG
---------------------------------------------------------------------------]]
BaseWars.DefaultConfig.PrinterPublic = false
BaseWars.DefaultConfig.PrinterPaperPrice = 25
BaseWars.DefaultConfig.SBoxWeaps = false
BaseWars.DefaultConfig.BankRadius = 0
BaseWars.DefaultConfig.WalkSpeed = 250
BaseWars.DefaultConfig.RunSpeed = 350
BaseWars.DefaultConfig.ChatCommandPrefix = "/"
BaseWars.DefaultConfig.RemoveProps = false
BaseWars.DefaultConfig.SpawnProtection = 5
BaseWars.DefaultConfig.AFKTime = 30
BaseWars.DefaultConfig.AllowPunt = false
BaseWars.DefaultConfig.WeaponBoxRemoveTime = 20
BaseWars.DefaultConfig.StartMoney = 20000
BaseWars.DefaultConfig.MaxLevel = 2000000000
BaseWars.DefaultConfig.XPMult = 1
BaseWars.DefaultConfig.PhysGunExplosive = false
BaseWars.DefaultConfig.MinPropHP = 1
BaseWars.DefaultConfig.MaxPropHP = 400
BaseWars.DefaultConfig.DispenserCooldown = .5
BaseWars.DefaultConfig.DefaultLimit = 4
BaseWars.DefaultConfig.EntityRenderDistance = 500
BaseWars.DefaultConfig.BackMoney = .8
BaseWars.DefaultConfig.GlobalImmunity = 150
BaseWars.DefaultConfig.FactionLimit = 5
BaseWars.DefaultConfig.DestroyReturn = .75
BaseWars.DefaultConfig.MaxBounty = -1
BaseWars.DefaultConfig.MaxPay = -1
BaseWars.DefaultConfig.RespawnTime = 3
BaseWars.DefaultConfig.DefaultLanguage = "en"
BaseWars.DefaultConfig.SuperAdminSpawnProps = true
BaseWars.DefaultConfig.AdminsSpawnProps = false
BaseWars.DefaultConfig.NotifyAllWhenConfigModified = true
BaseWars.DefaultConfig.DefaultHealth = 100
BaseWars.DefaultConfig.DefaultArmor = 100
BaseWars.DefaultConfig.GiveWeaponOnBuy = true
BaseWars.DefaultConfig.FactionCollision = true
BaseWars.DefaultConfig.ShutdownRefund = true
BaseWars.DefaultConfig.AdminIsVIP = true
BaseWars.DefaultConfig.BombsOpenDoors = true
BaseWars.DefaultConfig.MaxProfiles = 3
BaseWars.DefaultConfig.Debug = {
	SQL = false,
	Gamemode = false
}
BaseWars.DefaultConfig.AutoRestart = {
	Offset = 2,
	Enable = true,
	Interval = 12
}
BaseWars.DefaultConfig.CrashBackup = {
	Enable = true,
	Interval = 20
}
BaseWars.DefaultConfig.VIP = {
	["VIP"] = true
}
BaseWars.DefaultConfig.Admins = {
	["Moderator-Test"] = true,
	["Moderator"] = true,
	["admin"] = true,
}
BaseWars.DefaultConfig.SuperAdmins = {
	["superadmin"] = true,
}
BaseWars.DefaultConfig.PrinterCap = {
	["default"] = 26,
	["VIP"] = 28,
	["Moderator-Test"] = 28,
	["Moderator"] = 28,
	["admin"] = 28,
	["superadmin"] = 28,
}
BaseWars.DefaultConfig.PrinterMaxLevel = {
	["interval"] = 10,
	["amount"] = 30,
	["capacity"] = 15,
	["paperCapacity"] = 10
}
BaseWars.DefaultConfig.BankMaxLevel = {
	["capacity"] = 30,
	["health"] = 15
}
BaseWars.DefaultConfig.PayDay = {
	["VIP"] = .1,
	["Default"] = .025,
	["Time"] = 600,
	["AFKPayday"] = true
}
BaseWars.DefaultConfig.Raids = {
	["minimumLevel"] = 1200,
	["duration"] = 600,
	["immunity"] = 1800,
	["globalImmunity"] = 300,
	["shootPeopleInRaid"] = false,
	["cancelOnDisconnect"] = false
}
BaseWars.DefaultConfig.PhysgunPickupBlocked = {
	["bw_spawnpoint"] = true,
	["zrush_burner"] = true,
	["zrush_drilltower"] = true,
	["zrush_pump"] = true,
	["zrush_refinery"] = true,
	["zrush_drillhole"] = true,
	["zrms_refiner_coal"] = true,
	["zrms_refiner_iron"] = true,
	["zrms_refiner_bronze"] = true,
	["zrms_refiner_silver"] = true,
	["zrms_refiner_gold"] = true,
	["zrms_crusher"] = true,
	["zrms_conveyorbelt_n"] = true,
	["zrms_conveyorbelt_s"] = true,
	["zrms_conveyorbelt_c_left"] = true,
	["zrms_conveyorbelt_c_right"] = true,
	["zrms_inserter"] = true,
	["zrms_sorter_iron"] = true,
	["zrms_sorter_coal"] = true,
	["zrms_sorter_bronze"] = true,
	["zrms_sorter_silver"] = true,
	["zrms_sorter_gold"] = true,
	["zrms_splitter"] = true,
}
BaseWars.DefaultConfig.SpawnWeaps = {
	"weapon_physcannon",
	"hands",
}
BaseWars.DefaultConfig.WeaponDropBlacklist = {
	-- Default
	["gmod_tool"] = true,
	["gmod_camera"] = true,
	["weapon_physgun"] = true,
	["weapon_physcannon"] = true,
	["weapon_fists"] = true,
	["manhack_welder"] = true,
	["weapon_medkit"] = true,

	-- Half-Life 2
	["weapon_357"] = true,
	["weapon_pistol"] = true,
	["weapon_bugbait"] = true,
	["weapon_crossbow"] = true,
	["weapon_crowbar"] = true,
	["weapon_frag"] = true,
	["weapon_ar2"] = true,
	["weapon_rpg"] = true,
	["weapon_slam"] = true,
	["weapon_shotgun"] = true,
	["weapon_smg1"] = true,
	["weapon_stunstick"] = true,

	-- BaseWars
	["hands"] = true,
	["bw_grenade_gas"] = true,

	-- Addons?
	["pist_weagon"] = true,
	["weapon_zwhatisloveswep"] = true,
	["weapon_vazulaaa"] = true,
	["mg_xmike109"] = true,
	["guitar"] = true,
	["predator_bow"] = true,
	["weapon_nyangun"] = true,

	-- Taser
	["stungun_new"] = true,

	-- Other (or nil category)
	["weapon_luckygun"] = true,
	["weapon_popcorn"] = true,
	["weapon_popcorn_spam"] = true,
	["zpf_constructor"] = true,

	-- M9K
	["m9k_minigun"] = true,
}
BaseWars.DefaultConfig.CategoryBlackList = {
	["M9K Specialties"] = true,
	["Minecraft"] = true,
	["CS:GO Knives"] = true,
	["Counter-Strike: Global Offensive"] = true,
	["Vapes"] = true,
	["Sgt. Ownage"] = true,
	["Zeros GrowOP"] = true,
	["Zeros Meth Lab"] = true,
}
BaseWars.DefaultConfig.BlockedTools = {
	["axis"] = true,
	["ballsocket"] = true,
	["elastic"] = true,
	["hydraulic"] = true,
	["motor"] = true,
	["muscle"] = true,
	["pulley"] = true,
	["rope"] = true,
	["slider"] = true,
	["weld"] = true,
	["winch"] = true,
	["balloon"] = true,
	["duplicator"] = true,
	["dynamite"] = true,
	["emitter"] = true,
	["hoverball"] = true,
	["lamp"] = true,
	["nocollide"] = true,
	["physprop"] = true,
	["thruster"] = true,
	["wheel"] = true,
	["adv_bone"] = true,
	["eyeposer"] = true,
	["faceposer"] = true,
	["finger"] = true,
	["inflator"] = true,
	["inflator"] = true,
	["trails"] = true,
	["rb655_easy_animation"] = true,
	["rb655_easy_bodygroup"] = true,
	["rb655_easy_bonemerge"] = true,
	["animprop_gesturizer"] = true,
	["animprop_physify"] = true,
	["animprop_poseparams"] = true,
	["animprop"] = true,
	["shareprops"] = true,
	["permaprops"] = true,
	["zrush_oilspot_zoner"] = true,
	["zrmine_orespawner"] = true,
}
BaseWars.DefaultConfig.FormatNumber = {
	{1e33, "Decillion", "D"},
	{1e30, "Nonillion", "N"},
	{1e27, "Octillion", "O"},
	{1e24, "Septillion", "Sp"},
	{1e21, "Sextillion", "Sx"},
	{1e18, "Quintillion", "Qi"},
	{1e15, "Quadrillion", "Qa"},
	{1e12, "Trillion", "T"},
	{1e9, "Billion", "B"},
	{1e6, "Million", "M"}
}
BaseWars.DefaultConfig.WhitelistProps = {
	"models/props_lab/blastdoor001a.mdl",
	"models/props_lab/blastdoor001b.mdl",
	"models/props_lab/blastdoor001c.mdl",
	"models/props_phx/construct/metal_plate1.mdl",
	"models/props_phx/construct/metal_plate1_tri.mdl",
	"models/props_phx/construct/metal_plate1x2.mdl",
	"models/props_phx/construct/metal_plate2x2.mdl",
	"models/props_phx/construct/metal_plate2x2_tri.mdl",
	"models/props_phx/construct/metal_plate2x4.mdl",
	"models/props_phx/construct/metal_plate4x4.mdl",
	"models/props_phx/construct/metal_tube.mdl",
	"models/props_phx/construct/metal_tubex2.mdl",
	"models/hunter/plates/plate1x7.mdl",
	"models/hunter/plates/plate1x8.mdl",
	"models/hunter/plates/plate1x5.mdl",
	"models/hunter/plates/plate1x6.mdl",
	"models/props_c17/concrete_barrier001a.mdl",
	"models/hunter/triangles/1x1x1.mdl",
	"models/hunter/triangles/1x1x2.mdl",
	"models/hunter/triangles/1x1x3.mdl",
	"models/hunter/blocks/cube025x2x025.mdl",
	"models/hunter/blocks/cube1x2x1.mdl",
	"models/props_c17/FurnitureCouch001a.mdl",
	"models/props_c17/FurnitureCouch002a.mdl",
	"models/props_interiors/Furniture_Couch01a.mdl",
	"models/props_interiors/Furniture_Couch02a.mdl",
	"models/chairs/armchair.mdl",
}